#include "hal_data.h"

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

#define LED_BLUE    LED0
#define LED_GREEN   LED1
#define LED_RED     LED2
#define LED_ON      BSP_IO_LEVEL_LOW
#define LED_OFF     BSP_IO_LEVEL_HIGH

void setLED(const bsp_io_port_pin_t pin, const bsp_io_level_t state);

void setLED(const bsp_io_port_pin_t pin, const bsp_io_level_t state) {
    /* Enable access to the PFS registers. If using r_ioport module then register protection is automatically
     * handled. This code uses BSP IO functions to show how it is used.
     */
    R_BSP_PinAccessEnable();

    R_BSP_PinWrite(pin, state);

    /* Protect PFS registers */
    R_BSP_PinAccessDisable();
}

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* TODO: add your own code here */
    while(1) {
        setLED(LED_GREEN, LED_ON);
        R_BSP_SoftwareDelay(250, BSP_DELAY_UNITS_MILLISECONDS);

        setLED(LED_GREEN, LED_OFF);
        setLED(LED_RED, LED_ON);
        R_BSP_SoftwareDelay(250, BSP_DELAY_UNITS_MILLISECONDS);

        setLED(LED_RED, LED_OFF);
        setLED(LED_BLUE, LED_ON);
        R_BSP_SoftwareDelay(250, BSP_DELAY_UNITS_MILLISECONDS);

        setLED(LED_BLUE, LED_OFF);
        R_BSP_SoftwareDelay(250, BSP_DELAY_UNITS_MILLISECONDS);
    }

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart (bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
#if BSP_FEATURE_FLASH_LP_VERSION != 0

        /* Enable reading from data flash. */
        R_FACI_LP->DFLCTL = 1U;

        /* Would normally have to wait tDSTOP(6us) for data flash recovery. Placing the enable here, before clock and
         * C runtime initialization, should negate the need for a delay since the initialization will typically take more than 6us. */
#endif
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open(&g_ioport_ctrl, &IOPORT_CFG_NAME);
    }
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
